import { Box, Grid, Typography } from '@mui/material'
import Head from 'next/head'
import { ContactForm } from '../components/ContactForm'
import { Header } from '../components/Header'
import { ProductCard } from '../components/ProductCard'

export default function Home() {
  return (
    <Box>
      <Head>
        <title>OBP Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Header />
        <Box sx={{
          p: '0 80px',
          pt: '100px'
        }}>
          <Box sx={{
            textAlign: 'center',
            pb: '100px'
          }}>
            <Typography
              sx={{
                fontWeight: 700,
                fontSize: '36px'
              }}
            >
              Title
            </Typography>
          </Box>
          <Box sx={{
            pb: '100px'
          }}>
            <Grid container spacing={5}>
              <Grid item xs={3} spacing={3}>
                <ProductCard />
              </Grid>
              <Grid item xs={3} spacing={3}>
                <ProductCard />
              </Grid>
              <Grid item xs={3} spacing={3}>
                <ProductCard />
              </Grid>
              <Grid item xs={3} spacing={3}>
                <ProductCard />
              </Grid>
              <Grid item xs={3} spacing={3}>
                <ProductCard />
              </Grid>
              <Grid item xs={3} spacing={3}>
                <ProductCard />
              </Grid>
              <Grid item xs={3} spacing={3}>
                <ProductCard />
              </Grid>
              <Grid item xs={3} spacing={3}>
                <ProductCard />
              </Grid>
            </Grid>
          </Box>
        </Box>
        <Box sx={{
            display: 'flex',
            justifyContent: 'center',
            pt: '50px',
            pb: '50px',
            bgcolor: '#333333'
          }}>
            <ContactForm />
          </Box>
      </Box>
    </Box>
  )
}
